<Style name="roads-text-low-zoom">
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 1</Filter>
      &maxscale_zoom10;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield1.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 2</Filter>
      &maxscale_zoom10;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield2.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 3</Filter>
      &maxscale_zoom10;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield3.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 4</Filter>
      &maxscale_zoom10;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield4.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 5</Filter>
      &maxscale_zoom10;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield5.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 6</Filter>
      &maxscale_zoom10;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield6.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 7</Filter>
      &maxscale_zoom10;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield6.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 8</Filter>
      &maxscale_zoom10;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield7.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 1</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield1.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 2</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield2.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 3</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield3.png" min_distance="24" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 4</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield4.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 5</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield5.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 6</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield6.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 7</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield7.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 8</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield8.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 1</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield1.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 2</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield2.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 3</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield3.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 4</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield4.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 5</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield5.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 6</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield6.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 7</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield7.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 8</Filter>
      &maxscale_zoom11;
      &minscale_zoom12;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield8.png" min_distance="30" spacing="750"/>
    </Rule>
</Style>
<Style name="roads-text">
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 1</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield1.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 2</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield2.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 3</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield3.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 4</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield4.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 5</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield5.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 6</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield6.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 7</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield6.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'motorway' and [length] = 8</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield7.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 1</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield1.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 2</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield2.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 3</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield3.png" min_distance="24" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 4</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield4.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 5</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield5.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 6</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield6.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 7</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield7.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' and [length] = 8</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/aut_shield8.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 1</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield1.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 2</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield2.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 3</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield3.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 4</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield4.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 5</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield5.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 6</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield6.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 7</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield7.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'primary' and [length] = 8</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" placement="line" file="&symbols;/kra_shield8.png" min_distance="30" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'secondary' and [length] = 1) and not [bridge]='yes'</Filter>
      &maxscale_zoom12;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield1.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'secondary' and [length] = 2) and not [bridge]='yes'</Filter>
      &maxscale_zoom12;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield2.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'secondary' and [length] = 3) and not [bridge]='yes'</Filter>
      &maxscale_zoom12;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield3.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'secondary' and [length] = 4) and not [bridge]='yes'</Filter>
      &maxscale_zoom12;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield4.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'secondary' and [length] = 5) and not [bridge]='yes'</Filter>
      &maxscale_zoom12;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield5.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'secondary' and [length] = 6) and not [bridge]='yes'</Filter>
      &maxscale_zoom12;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield6.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'secondary' and [length] = 7) and not [bridge]='yes'</Filter>
      &maxscale_zoom12;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield7.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'secondary' and [length] = 8) and not [bridge]='yes'</Filter>
      &maxscale_zoom12;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield8.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'tertiary' and [length] = 1) and not [bridge]='yes'</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield1.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'tertiary' and [length] = 2) and not [bridge]='yes'</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield2.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'tertiary' and [length] = 3) and not [bridge]='yes'</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield3.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'tertiary' and [length] = 4) and not [bridge]='yes'</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield4.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'tertiary' and [length] = 5) and not [bridge]='yes'</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield5.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'tertiary' and [length] = 6) and not [bridge]='yes'</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield6.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'tertiary' and [length] = 7) and not [bridge]='yes'</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield7.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'tertiary' and [length] = 8) and not [bridge]='yes'</Filter>
      &maxscale_zoom13;
      &minscale_zoom18;
      <ShieldSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#fff" placement="line" file="&symbols;/raj_shield8.png" min_distance="40" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([highway] = 'unclassified' or [highway]='residential') and not [bridge]='yes'</Filter>
      &maxscale_zoom15;
      <TextSymbolizer name="ref" fontset_name="bold-fonts" size="10" fill="#000" halo_radius="1"  min_distance="18" spacing="750"/>
    </Rule>
    <Rule>
      <Filter>([aeroway] = 'runway' or [aeroway]='taxiway') and not [bridge]='yes'</Filter>
      &maxscale_zoom15;
      <TextSymbolizer name="ref" fontset_name="book-fonts" size="10" fill="#333" halo_radius="1"  min_distance="18" spacing="750" placement="line"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' or [highway] = 'primary'</Filter>
      &maxscale_zoom13;
      &minscale_zoom13;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="8" fill="black" halo_radius="0" placement="line"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'secondary'</Filter>
      &maxscale_zoom13;
      &minscale_zoom13;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="8" fill="black" halo_radius="1" halo_fill="#fed7a5" placement="line"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' or [highway] = 'primary'</Filter>
      &maxscale_zoom14;
      &minscale_zoom14;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="9" fill="black" halo_radius="0" placement="line"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'trunk' or [highway] = 'primary'</Filter>
      &maxscale_zoom15;
      &minscale_zoom18;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="10" fill="black" halo_radius="0" placement="line"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'secondary'</Filter>
      &maxscale_zoom14;
      &minscale_zoom14;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="9" fill="black" halo_radius="1" halo_fill="#fed7a5" placement="line"/>
    </Rule><Rule>
      <Filter>[highway] = 'secondary'</Filter>
      &maxscale_zoom15;
      &minscale_zoom18;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="10" fill="black" halo_radius="1" halo_fill="#fed7a5" placement="line"/>
    </Rule>
    <Rule>
      <Filter>[highway] = 'tertiary'</Filter>
      &maxscale_zoom15;
      &minscale_zoom16;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="9" fill="#000" halo_radius="1"  placement="line" />
    </Rule>
    <Rule>
      <Filter>[highway] = 'tertiary'</Filter>
      &maxscale_zoom17;
      &minscale_zoom18;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="11" fill="#000" halo_radius="1"  placement="line" />
    </Rule>
    <Rule>
      &maxscale_zoom13;
      &minscale_zoom15;
      <Filter>[highway] = 'proposed' or [highway]='construction'</Filter>
      <TextSymbolizer name="name" fontset_name="book-fonts" size="9" fill="#000" halo_radius="1"  placement="line" />
    </Rule>
    <Rule>
      &maxscale_zoom16;
      &minscale_zoom18;
      <Filter>[highway] = 'proposed' or [highway]='construction'</Filter>
      <TextSymbolizer name="name" fontset_name="book-fonts" size="11" fill="#000" halo_radius="1"  placement="line" />
    </Rule>
    <Rule>
      <Filter>[highway] = 'unclassified' or [highway] = 'residential'</Filter>
      &maxscale_zoom15;
      &minscale_zoom15;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="8" fill="#000" halo_radius="1" spacing="300" placement="line" />
    </Rule>
    <Rule>
      <Filter>[highway] = 'unclassified' or [highway] = 'residential'</Filter>
      &maxscale_zoom16;
      &minscale_zoom16;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="9" fill="#000" halo_radius="1" spacing="300" placement="line" />
    </Rule>
    <Rule>
      <Filter>[highway] = 'unclassified' or [highway] = 'residential'</Filter>
      &maxscale_zoom17;
      &minscale_zoom18;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="11" fill="#000" halo_radius="1" spacing="400" placement="line" />
    </Rule>
    <Rule>
      <ElseFilter/>
      &maxscale_zoom15;
      &minscale_zoom16;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="9" fill="#000" halo_radius="1" placement="line" />
    </Rule>
    <Rule>
      <ElseFilter/>
      &maxscale_zoom17;
      &minscale_zoom18;
      <TextSymbolizer name="name" fontset_name="book-fonts" size="11" fill="#000" halo_radius="1" placement="line" />
    </Rule>
</Style>
<Layer name="planet roads text osm low zoom" status="on" srs="&osm2pgsql_projection;" maxzoom="&max_zoom10;" minzoom="&min_zoom12;">
     <StyleName>roads-text-low-zoom</StyleName>
     <Datasource>
      <Parameter name="table">
      (select way,highway,ref,char_length(ref) as length
       from &prefix;_roads
       where highway in ('motorway','trunk','primary')
         and ref is not null
      ) as roads
      </Parameter>
      &datasource-settings;
    </Datasource>
</Layer>
<Layer name="planet roads text osm" status="on" srs="&osm2pgsql_projection;" maxzoom="&max_zoom12;">
     <StyleName>roads-text</StyleName>
     <Datasource>
      <Parameter name="table">
      (select way,highway,aeroway,name,ref,char_length(ref) as length,
       case when bridge in ('yes','true','1') then 'yes'::text else bridge end as bridge
       from &prefix;_line
       where waterway IS NULL
         and leisure IS NULL
         and landuse IS NULL
         and (name is not null or ((highway is not null or aeroway is not null) and ref is not null))
      ) as roads
      </Parameter>
      &datasource-settings;
    </Datasource>
</Layer>
